### ISSUE TITLE
php70u-ast

### ISSUE THREAD

**Issue by christopherowen** [iuscommunity/wishlist#54]
### What package do you want?

the AST extension for php 7
### Why?

It's a dependency for the 'phan' static code analyzer by esty. https://www.github.com/etsy/phan
### OS versions

I would like this package for both RHEL 6 and 7.
### Testing

I agree to test the new package to ensure that it works as expected.

**Comment by christopherowen** [comment]
php-ast is available from here: 

https://www.github.com/nikic/php-ast

**Comment by carlwgeorge** [comment]
Howdy @christopherowen.  Thanks for taking the time to make a request.

IUS stands for Inline with Upstream Stable.  This software's [readme file](https://github.com/nikic/php-ast/blob/master/README.md) describes it as "experimental".  You should contact the upstream to see if that is still accurate.  Once there is a release that the upstream considers "stable", we will re-evaluate this as a package.

FYI, I did see in one of their open [issues](https://github.com/nikic/php-ast/issues/5) that an [RFC](https://wiki.php.net/rfc/parser-extension-api) has been submitted to add this to the core PHP code base.

**Comment by christopherowen** [comment]
https://github.com/nikic/php-ast/issues/25

**Comment by melz** [comment]
They have dropped the "experimental" tag from the readme. Any chance that to get this package re-evaluated for inclusion in IUS?

**Comment by carlwgeorge** [comment]
The [RFC](https://wiki.php.net/rfc/abstract_syntax_tree) was accepted and states that it is implemented in PHP 7.  Checking the source, I see that zend_ast.c exists in both [7.0](https://github.com/php/php-src/blob/php-7.0.0/Zend/zend_ast.c) and [7.1](https://github.com/php/php-src/blob/PHP-7.1.0/Zend/zend_ast.c).  I don't know what the point of making this as a separate package is.

**Comment by christopherowen** [comment]
This remains to be a going concern. 

It's not possible to use phan without taking action outside of yum to configure php-ast for php70u.

```
[root@control01 ~]# rpm -qa | grep php | sort
mod_php70u-7.0.18-1.ius.centos7.x86_64
php70u-cli-7.0.18-1.ius.centos7.x86_64
php70u-common-7.0.18-1.ius.centos7.x86_64
php70u-gd-7.0.18-1.ius.centos7.x86_64
php70u-intl-7.0.18-1.ius.centos7.x86_64
php70u-json-7.0.18-1.ius.centos7.x86_64
php70u-mysqlnd-7.0.18-1.ius.centos7.x86_64
php70u-pdo-7.0.18-1.ius.centos7.x86_64
php70u-pear-1.10.4-1.ius.centos7.noarch
php70u-pecl-igbinary-2.0.1-1.ius.centos7.x86_64
php70u-pecl-imagick-3.4.3-1.ius.centos7.x86_64
php70u-pecl-memcached-3.0.3-1.ius.centos7.x86_64
php70u-process-7.0.18-1.ius.centos7.x86_64
php70u-soap-7.0.18-1.ius.centos7.x86_64
php70u-xml-7.0.18-1.ius.centos7.x86_64
```

```
[user@server ~]# phan --help
PHP Fatal error:  Uncaught Error: Undefined constant 'ast\flags\USE_NORMAL' in phar:///usr/local/bin/phan/src/Phan/Language/FQSEN/FullyQualifiedClassName.php:21
Stack trace:
#0 phar:///usr/local/bin/phan/src/Phan/Language/FQSEN/FullyQualifiedGlobalStructuralElement.php(174): Phan\Language\FQSEN\FullyQualifiedClassName::getNamespaceMapType()
#1 phar:///usr/local/bin/phan/src/Phan/Language/Element/Clazz.php(164): Phan\Language\FQSEN\FullyQualifiedGlobalStructuralElement::fromStringInContext('stdClass', Object(Phan\Language\Context))
#2 phar:///usr/local/bin/phan/src/Phan/Language/Element/Clazz.php(127): Phan\Language\Element\Clazz::fromReflectionClass(Object(Phan\CodeBase), Object(ReflectionClass))
#3 phar:///usr/local/bin/phan/src/Phan/CodeBase.php(143): Phan\Language\Element\Clazz::fromClassName(Object(Phan\CodeBase), 'stdClass')
#4 phar:///usr/local/bin/phan/src/Phan/CodeBase.php(118): Phan\CodeBase->addClassesByNames(Array)
#5 phar:///usr/local/bin/phan/src/codebase.php(21): Phan\CodeBase->__construct(Array, Array, Array, Ar in phar:///usr/local/bin/phan/src/Phan/Language/FQSEN/FullyQualifiedClassName.php on line 21
```

**Comment by b-harper** [comment]
Hey @christopherowen,

I have done some additional research and have gained a greater understanding of PHP's Abstract Syntax Tree (AST), the role of php-ast and the needs of phan. I am able to recreate output from you last update via a slightly different method:

```
# curl -L https://github.com/etsy/phan/releases/download/0.8.3/phan.phar -o phan.phar;
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   587    0   587    0     0   3540      0 --:--:-- --:--:-- --:--:--  3557
100 21.4M  100 21.4M    0     0  22.9M      0 --:--:-- --:--:-- --:--:-- 33.5M
# php phan.phar --help
PHP Fatal error:  Uncaught Error: Undefined constant 'ast\flags\USE_NORMAL' in phar:///root/ben/phan/phan.phar/src/Phan/Language/FQSEN/FullyQualifiedClassName.php:21
Stack trace:
#0 phar:///root/ben/phan/phan.phar/src/Phan/Language/FQSEN/FullyQualifiedGlobalStructuralElement.php(174): Phan\Language\FQSEN\FullyQualifiedClassName::getNamespaceMapType()
#1 phar:///root/ben/phan/phan.phar/src/Phan/Language/Element/Clazz.php(164): Phan\Language\FQSEN\FullyQualifiedGlobalStructuralElement::fromStringInContext('stdClass', Object(Phan\Language\Context))
#2 phar:///root/ben/phan/phan.phar/src/Phan/Language/Element/Clazz.php(127): Phan\Language\Element\Clazz::fromReflectionClass(Object(Phan\CodeBase), Object(ReflectionClass))
#3 phar:///root/ben/phan/phan.phar/src/Phan/CodeBase.php(143): Phan\Language\Element\Clazz::fromClassName(Object(Phan\CodeBase), 'stdClass')
#4 phar:///root/ben/phan/phan.phar/src/Phan/CodeBase.php(118): Phan\CodeBase->addClassesByNames(Array)
#5 phar:///root/ben/phan/phan.phar/src/codebase.php(21): Phan\CodeBase-> in phar:///root/ben/phan/phan.phar/src/Phan/Language/FQSEN/FullyQualifiedClassName.php on line 21
```
After manually compiling php-ast, it appears to work correctly.

<details>

```
# php phan.phar --help
Usage: phan.phar [options] [files...]
 -f, --file-list <filename>
  A file containing a list of PHP files to be analyzed

 -r, --file-list-only
  A file containing a list of PHP files to be analyzed to the
  exclusion of any other directories or files passed in.

 -l, --directory <directory>
  A directory that should be parsed for class and
  method information. After excluding the directories
  defined in --exclude-directory-list, the remaining
  files will be statically analyzed for errors.

  Thus, both first-party and third-party code being used by
  your application should be included in this list.

  You may include multiple `--directory DIR` options.

 --exclude-file <file>
  A file that should not be parsed or analyzed (or read
  at all). This is useful for excluding hopelessly
  unanalyzable files.

 -3, --exclude-directory-list <dir_list>
  A comma-separated list of directories that defines files
  that will be excluded from static analysis, but whose
  class and method information should be included.

  Generally, you'll want to include the directories for
  third-party code (such as "vendor/") in this list.

 -d, --project-root-directory
  Hunt for a directory named .phan in the current or parent
  directory and read configuration file config.php from that
  path.

 -k, --config-file
  A path to a config file to load (instead of the default of
  .phan/config.php).

 -m <mode>, --output-mode
  Output mode from 'text', 'json', 'csv', 'codeclimate', 'checkstyle', or 'pylint'

 -o, --output <filename>
  Output filename

 -p, --progress-bar
  Show progress bar

 -a, --dump-ast
  Emit an AST for each file rather than analyze

 --dump-signatures-file <filename>
  Emit JSON serialized signatures to the given file.
  This uses a method signature format similar to FunctionSignatureMap.php.

 -q, --quick
  Quick mode - doesn't recurse into all function calls

 -b, --backward-compatibility-checks
  Check for potential PHP 5 -> PHP 7 BC issues

 -i, --ignore-undeclared
  Ignore undeclared functions and classes

 -y, --minimum-severity <level in {0,5,10}>
  Minimum severity level (low=0, normal=5, critical=10) to report.
  Defaults to 0.

 -c, --parent-constructor-required
  Comma-separated list of classes that require
  parent::__construct() to be called

 -x, --dead-code-detection
  Emit issues for classes, methods, functions, constants and
  properties that are probably never referenced and can
  possibly be removed.

 -j, --processes <int>
  The number of parallel processes to run during the analysis
  phase. Defaults to 1.

 -z, --signature-compatibility
  Analyze signatures for methods that are overrides to ensure
  compatibility with what they're overriding.

 -h,--help
  This help information
```
</details>


I'll take a look what involved in creating some php70u-ast packages.

**Comment by b-harper** [comment]
[An initial  spec file][spec] has been created and packages will be hitting the testing repositories during tonight's automation run.  

[spec]: https://github.com/iuscommunity-pkg/php70u-ast

**Comment by b-harper** [comment]
@melz,  

I wanted to check in and see if you have had a chance to test this package.

**Comment by b-harper** [comment]
@christopherowen, @melz, I am curious if you have had the time to test this package.  Please let us know if it works for your needs.

**Comment by b-harper** [comment]
Seeing that we have not gotten feedback on this package in roughly two months, I am going to move this package to the development repositories and close this request.  If the issues gets updated with feedback, we will promote the package to the stable repositories.
